### PR TITLE
Alex's portion

### PR DESCRIPTION
**Pull request by AlexRivas676**
add user object and created user sign up ui page in main.storyboard

### CODE REVIEW

**Review by Andalv323 — CHANGES_REQUESTED** [review]
Take out your version of .gitignore , can't combine them.

**Comment by Andalv323** [comment]
I fixed it

**Comment by Andalv323** [comment]
Test it it on your end to make sure i didnt change anything

**Comment by AlexRivas676** [comment]
Everything looks good and it still works we just have to  add login  logic
and signup logic i can try to add the signup logic if you have  too much of
a  workload and  I'll try to get in contact with Ruth to see if she can add
the login logic that she did.

**Pull request merged**
